language: python

# Setting sudo to false opts in to Travis-CI container-based builds.
sudo: false

python:
    - 3.6

addons:
    apt:
        packages:
            # Used for Spginx 
            - graphviz
            - texlive-latex-extra
            - dvipng

env:
    global:
        # The following versions are the 'default' for tests, unless
        # overridden underneath. They are defined here in order to save having
        # to repeat them for all configurations.
        - NUMPY_VERSION=stable
        - ASTROPY_VERSION=stable
        - POPPY_VERSION=development
        - CONDA_INSTALL='conda install --yes'
        - PIP_INSTALL='pip install'
        # For headless testing of code that imports PyPlot:
        - MPLBACKEND=Agg
    matrix:
        # Make sure that egg_info works without dependencies
        - SETUP_CMD='egg_info'

matrix:
    include:
        # do the actual tests.
        # Do a coverage test in Python 3.
        #- python: 3.5
        #  env: SETUP_CMD='test --coverage'

        # Try all supported Python versions with the latest NumPy
        # and other dependencies
        - python: 3.6
          env: SETUP_CMD='test'

              
before_install:

    # Use utf8 encoding. Should be default, but this is insurance against
    # future changes
    - export PYTHONIOENCODING=UTF8
    # Prefer Agg backend in case PyPlot is imported
    # (see http://matplotlib.org/faq/environment_variables_faq.html)
    - export MPLBACKEND=Agg
    - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
    - chmod +x miniconda.sh
    - ./miniconda.sh -b
    - export PATH=/home/travis/miniconda2/bin:$PATH
    - conda update --yes conda

install:
    # See https://github.com/astropy/ci-helpers for docs on
    # how this setup works
    - git clone --depth 1 git://github.com/astropy/ci-helpers.git
    - source ci-helpers/travis/setup_conda.sh
    # COVERAGE DEPENDENCIES
    - if [[ $SETUP_CMD == 'test --coverage' ]]; then $PIP_INSTALL coverage coveralls; fi

before_script:

script:
   - python setup.py $SETUP_CMD

after_success:
    # If coveralls.io is set up for this package, uncomment the line
    # below and replace "packagename" with the name of your package.
    # The coveragerc file may be customized as needed for your package.
    - if [[ $SETUP_CMD == 'test --coverage' ]]; then coveralls --rcfile='gpypsfs/tests/coveragerc'; fi

notifications:
  email:
    - mperrin@stsci.edu
